/**
 * discipline:rls-generate — Generates a Supabase migration SQL file for a new table
 * with full RLS setup, indexes, and updated_at trigger.
 *
 * Usage:
 *   node tools/generate_rls.js --table items --collab COLLABORATIVE
 *   node tools/generate_rls.js --table items --collab VIEW_ONLY
 *   node tools/generate_rls.js --table items --output supabase/migrations/001_items.sql
 *
 * If --collab is omitted, reads COLLAB_MODE from discipline.md.
 */

import fs from 'node:fs';
import path from 'node:path';
import { parseArgs } from 'node:util';

const VALID_COLLAB_MODES = ['COLLABORATIVE', 'VIEW_ONLY'];

// ── CLI args ────────────────────────────────────────────────────────────────

const { values } = parseArgs({
  options: {
    table:  { type: 'string', short: 't' },
    collab: { type: 'string', short: 'c' },
    output: { type: 'string', short: 'o' },
  },
  strict: false,
});

if (!values.table) {
  console.error('Error: --table <name> is required.');
  console.error('Usage: node tools/generate_rls.js --table <name> [--collab COLLABORATIVE|VIEW_ONLY] [--output <path>]');
  process.exit(1);
}

const tableName = values.table;

// ── Resolve COLLAB_MODE ─────────────────────────────────────────────────────

function readCollabModeFromDiscipline(root = process.cwd()) {
  const disciplinePath = path.join(root, 'discipline.md');
  if (!fs.existsSync(disciplinePath)) return null;
  const content = fs.readFileSync(disciplinePath, 'utf-8');
  const match = content.match(/-\s+COLLAB_MODE:\s*([^#\r\n]+)/);
  return match ? match[1].trim() : null;
}

let collabMode = values.collab ?? readCollabModeFromDiscipline();

if (!collabMode) {
  console.error('Error: --collab not provided and COLLAB_MODE not set in discipline.md.');
  console.error('Specify --collab COLLABORATIVE or --collab VIEW_ONLY.');
  process.exit(1);
}

collabMode = collabMode.toUpperCase();

if (!VALID_COLLAB_MODES.includes(collabMode)) {
  console.error(`Error: Invalid collab mode "${collabMode}". Must be one of: ${VALID_COLLAB_MODES.join(', ')}`);
  process.exit(1);
}

// ── SQL generation ──────────────────────────────────────────────────────────

function generateSQL(table, mode) {
  const isCollaborative = mode === 'COLLABORATIVE';

  const selectUsing = `EXISTS (
      SELECT 1 FROM public.space_members sm
      WHERE sm.space_id = ${table}.space_id
        AND sm.user_id = auth.uid()
    )`;

  const ownerOnly = `auth.uid() = ${table}.created_by`;

  const insertCheck = isCollaborative ? selectUsing : ownerOnly;
  const updateUsing = isCollaborative ? selectUsing : ownerOnly;
  const updateCheck = isCollaborative ? selectUsing : ownerOnly;
  const deleteUsing = isCollaborative ? selectUsing : ownerOnly;

  return `-- Generated by discipline:rls-generate for table: ${table} (COLLAB_MODE: ${mode})
-- Review and customize before applying. Move to supabase/migrations/ when ready.

-- ============================================================================
-- Table: ${table}
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.${table} (
  id         UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  space_id   UUID        NOT NULL REFERENCES public.spaces(id) ON DELETE CASCADE,
  created_by UUID        NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
  -- Add your columns here. Add a comma before new columns.
);

-- ── Row Level Security ──────────────────────────────────────────────────────

ALTER TABLE public.${table} ENABLE ROW LEVEL SECURITY;

-- NOTE (RLS + RETURNING, FINDING-04): this SELECT policy is membership-based. For this
-- CHILD table, it is safe: the inserting user is already a space member, so .insert().select()
-- (return=representation) works. But if you carry this pattern to a ROOT table whose
-- membership is created by an AFTER trigger on its own insert (for example a "spaces" table),
-- .insert().select() will return 403: RETURNING evaluates the SELECT policy before the
-- trigger-created membership row is visible. Fix: add "OR auth.uid() = ${table}.created_by" to
-- that table's SELECT policy, or insert with return=minimal (without .select()).
-- SELECT: any space member can read
CREATE POLICY "${table}_select" ON public.${table}
  FOR SELECT USING (
    ${selectUsing}
  );

-- INSERT: ${isCollaborative ? 'any space member' : 'only the owner'} can insert
CREATE POLICY "${table}_insert" ON public.${table}
  FOR INSERT WITH CHECK (
    ${insertCheck}
  );

-- UPDATE: ${isCollaborative ? 'any space member' : 'only the owner'} can update
CREATE POLICY "${table}_update" ON public.${table}
  FOR UPDATE USING (
    ${updateUsing}
  ) WITH CHECK (
    ${updateCheck}
  );

-- DELETE: ${isCollaborative ? 'any space member' : 'only the owner'} can delete
CREATE POLICY "${table}_delete" ON public.${table}
  FOR DELETE USING (
    ${deleteUsing}
  );

-- ── Indexes ─────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_${table}_space_id    ON public.${table}(space_id);
CREATE INDEX IF NOT EXISTS idx_${table}_created_by  ON public.${table}(created_by);

-- ── Trigger: auto-update updated_at ─────────────────────────────────────────

CREATE TRIGGER set_${table}_updated_at
  BEFORE UPDATE ON public.${table}
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();
`;
}

// ── Output ──────────────────────────────────────────────────────────────────

const sql = generateSQL(tableName, collabMode);

if (values.output) {
  const outPath = path.resolve(values.output);
  const outDir = path.dirname(outPath);
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  fs.writeFileSync(outPath, sql, 'utf-8');
  console.log(`[discipline:rls-generate] Written to ${outPath}`);
} else {
  process.stdout.write(sql);
}
