#!/usr/bin/env npx tsx
/**
 * discipline:step1-prep - Generates Step 1 input files and prompt reference.
 *
 * Reads IDEA_VALIDATION_PACKET (if it exists) + discipline.md switches.
 * Produces:
 *   .discipline/step1-input/00_Raw_Input.md
 *   .discipline/step1-input/01_Real_Examples.md
 *   .discipline/step1-input/02_Constraints.md
 *   .discipline/prompts/step-1-all-prompts.md  (all 13 prompts, interpolated)
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { resolveProjectRoot, readDisciplineConfig } from './lib/discipline-config.js';
import { disciplineInfo } from './lib/types.js';
import { systemPrompt, getPrompt, OUTPUT_META } from './lib/step1-prompts.js';

const root = resolveProjectRoot();
const config = readDisciplineConfig(root);

const inputDir = path.join(root, '.discipline', 'step1-input');
const promptsDir = path.join(root, '.discipline', 'prompts');
fs.mkdirSync(inputDir, { recursive: true });
fs.mkdirSync(promptsDir, { recursive: true });

const packetPath = path.join(root, '.discipline', 'packets', 'IDEA_VALIDATION_PACKET.md');
const hasPacket = fs.existsSync(packetPath);
const packetContent = hasPacket ? fs.readFileSync(packetPath, 'utf-8') : '';

const rawInput = hasPacket
  ? `# Raw Input - ${config.projectName}

## IDEA_VALIDATION_PACKET (from Step 0a)

${packetContent}

---

## Additional context

Add any extra details that are not in the packet:

- What screens do you imagine?
- What data will it store?
- What do you hate about current alternatives?
- Screenshots or URLs of reference apps (if you have them)
`
  : `# Raw Input - ${config.projectName}

Paste everything you have about the idea here, without over-organizing it:

- What problem does it solve?
- Who is it for?
- Why does it matter to you?
- What screens do you imagine?
- What data will it store?
- Does it require sync? Notifications? AI?
- Will you use it yourself, with a trusted group, or publicly?
- What would "success" mean?
- What do you hate about current alternatives?
- Screenshots or URLs of reference apps (if you have them)
`;

const examples = `# Real Examples - ${config.projectName}

Add 5-15 concrete usage examples:

Case 1:
- I want to be able to...
- Ideal outcome...

Case 2:
- My shared group should be able to...
- Ideal outcome...

Case 3:
- On iPhone I want...
- On PC I want...
`;

const constraints = `# Constraints - ${config.projectName}

## Already chosen switches
- LANE: ${config.lane}
- PROFILE: ${config.profile}
- BACKEND_PROVIDER: ${config.backendProvider}
- AUTH_MODE: ${config.authMode}
- COLLAB_MODE: ${config.collabMode}
- SYNC_MODE: ${config.syncMode}
- AI_FEATURES: ${config.aiFeatures}
- PUSH_PLUGIN: ${config.pushPlugin}
- HOSTING: ${config.hosting || '(undecided)'}

## Additional constraints

Complete based on your case:

- Maximum monthly cost:
- Expected speed:
- Least debugging possible: yes
- Multi-device: ${config.profile === 'SHARED_SYNC' ? 'yes' : 'no'}
- Shared: ${config.profile === 'SHARED_SYNC' ? 'yes' : 'no'}
- Offline matters: ${config.syncMode === 'OFFLINE_FIRST' ? 'yes' : 'no'}
- Privacy: high / medium / low
- Sell later: yes / no
`;

fs.writeFileSync(path.join(inputDir, '00_Raw_Input.md'), rawInput);
fs.writeFileSync(path.join(inputDir, '01_Real_Examples.md'), examples);
fs.writeFileSync(path.join(inputDir, '02_Constraints.md'), constraints);
disciplineInfo(`Input files generated in ${inputDir}`);

let allPrompts = `# Step 1 - Prompts
# Project: ${config.projectName}
# Generated by: discipline:step1-prep
# Date: ${new Date().toISOString().split('T')[0]}

---

## SYSTEM PROMPT (paste into chat configuration -> custom/system instructions)

\`\`\`
${systemPrompt(config)}
\`\`\`

---

`;

for (const meta of OUTPUT_META) {
  const skip = !meta.condition(config);
  const skipNote = skip ? ' **(SKIP - condition does not apply)**' : '';
  const prompt = getPrompt(meta.number, config);

  allPrompts += `## Output ${meta.number} - ${meta.noteTitle}${skipNote}

**Save as:** ${meta.packetFile ? `\`.discipline/packets/${meta.packetFile}\`` : `intermediate output \`${meta.noteTitle}\` (does not generate a packet)`}
${skip ? '\n> This output is skipped because the condition does not apply to this project.\n' : ''}
\`\`\`
${prompt}
\`\`\`

---

`;
}

fs.writeFileSync(path.join(promptsDir, 'step-1-all-prompts.md'), allPrompts);
disciplineInfo(`Prompt file generated in ${path.join(promptsDir, 'step-1-all-prompts.md')}`);

const activeOutputs = OUTPUT_META.filter(m => m.condition(config)).length;
console.log(`
+----------------------------------------------------------+
|  discipline:step1-prep completed                         |
+----------------------------------------------------------+
|  Project: ${config.projectName.padEnd(43)}|
|  LANE: ${config.lane.padEnd(48)}|
|  Active outputs: ${String(activeOutputs).padEnd(36)}|
|  IDEA_VALIDATION_PACKET: ${(hasPacket ? 'yes' : 'no').padEnd(29)}|
+----------------------------------------------------------+
|  Generated files:                                        |
|  .discipline/step1-input/00_Raw_Input.md                 |
|  .discipline/step1-input/01_Real_Examples.md             |
|  .discipline/step1-input/02_Constraints.md               |
|  .discipline/prompts/step-1-all-prompts.md               |
+----------------------------------------------------------+
|  Next:                                                   |
|  Automated mode: /discipline-step1                       |
|  Manual mode: open step-1-all-prompts.md and follow order|
+----------------------------------------------------------+
`);