/**
 * discipline:test-scaffold
 *
 * Reads discipline.md contracts (data model, API shapes, sync rules)
 * and generates test stubs: 1 happy path + 1 error path per contract.
 *
 * Usage:
 *   npm run discipline:test-scaffold
 *   npm run discipline:test-scaffold -- --output tests/generated/
 *
 * Generates:
 * - Backend adapter tests (ensurePersonalSpace, listNotifications, etc.)
 * - RLS policy tests if BACKEND=SUPABASE
 * - API endpoint tests if LANE=BACKEND
 * - UI state tests for each screen in UI_HANDOFF_PACKET
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import minimist from 'minimist';
import { disciplineInfo, disciplineError } from './lib/types.js';
import { resolveProjectRoot, readDisciplineConfig } from './lib/discipline-config.js';

const args = minimist(process.argv.slice(2));
const projectRoot = resolveProjectRoot(args['project-dir']);
const outputDir = args.output || path.join(projectRoot, 'tests', 'generated');

function readIfExists(filePath: string): string | null {
  return fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf-8') : null;
}

function extractEntities(disciplineContent: string): string[] {
  const dataModelSection = disciplineContent.match(/## 3\) Data Model([\s\S]*?)## 4\)/);
  if (!dataModelSection) return [];

  const entities: string[] = [];
  const matches = dataModelSection[1].matchAll(/(?:table|entity|collection|type)\s*[:`]\s*(\w+)/gi);
  for (const m of matches) {
    if (!['N/A', 'undefined', 'null'].includes(m[1])) entities.push(m[1]);
  }

  // Also extract from markdown headers like "### spaces" or "### items"
  const headerMatches = dataModelSection[1].matchAll(/###\s+(\w+)/g);
  for (const m of headerMatches) {
    if (!entities.includes(m[1]) && m[1].length > 2) entities.push(m[1]);
  }

  return [...new Set(entities)];
}

function extractApiEndpoints(disciplineContent: string): Array<{ method: string; path: string; description: string }> {
  const apiSection = disciplineContent.match(/## 4\) API \/ IO Shapes([\s\S]*?)## 5\)/);
  if (!apiSection) return [];

  const endpoints: Array<{ method: string; path: string; description: string }> = [];
  const matches = apiSection[1].matchAll(/(GET|POST|PUT|PATCH|DELETE)\s+([/\w{}:-]+)\s*[-:]?\s*(.*)/gi);
  for (const m of matches) {
    endpoints.push({ method: m[1].toUpperCase(), path: m[2], description: m[3].trim() });
  }
  return endpoints;
}

function extractScreens(packetsDir: string): string[] {
  const uiPacket = readIfExists(path.join(packetsDir, 'UI_HANDOFF_PACKET.md'));
  if (!uiPacket) return [];

  const screens: string[] = [];
  const matches = uiPacket.matchAll(/##\s+SCREEN:\s*(.+)/gi);
  for (const m of matches) screens.push(m[1].trim());
  return screens;
}

function generateBackendTests(entities: string[], _config: ReturnType<typeof readDisciplineConfig>): string {
  const tests: string[] = [
    `import { describe, it, expect } from '@jest/globals';`,
    `// Generated by discipline:test-scaffold from discipline.md contracts`,
    `// Fill in the implementation details for each test`,
    ``,
    `describe('Backend adapter contracts', () => {`,
    `  describe('Auth', () => {`,
    `    it('should return null when no user is signed in', async () => {`,
    `      // TODO: const backend = await getBackend();`,
    `      // TODO: const user = await backend.auth.getUser();`,
    `      // TODO: expect(user).toBeNull();`,
    `    });`,
    ``,
    `    it('should handle sign-in error gracefully', async () => {`,
    `      // TODO: Test with invalid email or expired link`,
    `    });`,
    `  });`,
    ``,
    `  describe('Core', () => {`,
    `    it('should create a personal space for new user (happy path)', async () => {`,
    `      // TODO: const { space, membership } = await backend.core.ensurePersonalSpace();`,
    `      // TODO: expect(space.id).toBeDefined();`,
    `      // TODO: expect(membership.role).toBe('owner');`,
    `    });`,
    ``,
    `    it('should return existing space on second call (idempotent)', async () => {`,
    `      // TODO: Call ensurePersonalSpace twice, verify same space returned`,
    `    });`,
    ``,
    `    it('should list notifications filtered by space', async () => {`,
    `      // TODO: Verify notifications don't leak across spaces`,
    `    });`,
    ``,
    `    it('should reject marking notification from another space', async () => {`,
    `      // TODO: Verify cross-space isolation`,
    `    });`,
    `  });`,
  ];

  for (const entity of entities) {
    if (['spaces', 'memberships', 'notifications'].includes(entity.toLowerCase())) continue;
    tests.push(``, `  describe('${entity}', () => {`);
    tests.push(`    it('should create a ${entity} within a space (happy path)', async () => {`);
    tests.push(`      // TODO: Create ${entity}, verify space_id is set`);
    tests.push(`    });`);
    tests.push(``);
    tests.push(`    it('should reject ${entity} without valid space_id (error path)', async () => {`);
    tests.push(`      // TODO: Attempt create with missing/invalid space_id`);
    tests.push(`    });`);
    tests.push(`  });`);
  }

  tests.push(`});`);
  return tests.join('\n');
}

function generateRlsTests(entities: string[], config: ReturnType<typeof readDisciplineConfig>): string {
  const collabMode = config.collabMode || 'VIEW_ONLY';
  const tests: string[] = [
    `// Generated by discipline:test-scaffold - Supabase RLS policy tests`,
    `// These tests require a real Supabase connection (integration tests)`,
    `// Run with: SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... jest rls.test.ts`,
    ``,
    `import { describe, it, expect } from '@jest/globals';`,
    ``,
    `describe('RLS Policies (COLLAB_MODE=${collabMode})', () => {`,
  ];

  const allEntities = ['spaces', 'memberships', 'notifications', ...entities.filter(
    e => !['spaces', 'memberships', 'notifications'].includes(e.toLowerCase())
  )];

  for (const entity of allEntities) {
    tests.push(`  describe('${entity}', () => {`);
    tests.push(`    it('owner can read own space ${entity}', async () => {`);
    tests.push(`      // TODO: Authenticate as owner, query ${entity}, expect results`);
    tests.push(`    });`);
    tests.push(``);
    tests.push(`    it('member cannot read other space ${entity}', async () => {`);
    tests.push(`      // TODO: Authenticate as member of space A, query ${entity} of space B, expect empty`);
    tests.push(`    });`);

    if (collabMode === 'VIEW_ONLY') {
      tests.push(``);
      tests.push(`    it('member cannot insert into ${entity} (VIEW_ONLY)', async () => {`);
      tests.push(`      // TODO: Authenticate as member, attempt INSERT, expect denied`);
      tests.push(`    });`);
    }

    tests.push(`  });`);
    tests.push(``);
  }

  tests.push(`});`);
  return tests.join('\n');
}

function generateApiTests(endpoints: Array<{ method: string; path: string; description: string }>): string {
  const tests: string[] = [
    `// Generated by discipline:test-scaffold - API endpoint tests`,
    `// Adjust BASE_URL and auth headers for your environment`,
    ``,
    `import { describe, it, expect } from '@jest/globals';`,
    ``,
    `const BASE_URL = process.env.API_URL || 'http://localhost:3000';`,
    ``,
    `describe('API Endpoints', () => {`,
  ];

  for (const ep of endpoints) {
    const testName = `${ep.method} ${ep.path}${ep.description ? ` - ${ep.description}` : ''}`;
    tests.push(`  describe('${testName}', () => {`);
    tests.push(`    it('happy path: returns expected response', async () => {`);
    tests.push(`      // TODO: const res = await fetch(\`\${BASE_URL}${ep.path}\`, { method: '${ep.method}' });`);
    tests.push(`      // TODO: expect(res.status).toBe(200);`);
    tests.push(`    });`);
    tests.push(``);
    tests.push(`    it('error path: handles invalid input', async () => {`);
    tests.push(`      // TODO: Send malformed request, expect 400 or appropriate error`);
    tests.push(`    });`);
    tests.push(`  });`);
    tests.push(``);
  }

  tests.push(`});`);
  return tests.join('\n');
}

function generateUiStateTests(screens: string[]): string {
  const tests: string[] = [
    `// Generated by discipline:test-scaffold - UI state tests`,
    `// Verify that each screen handles all 4 required states`,
    ``,
    `import { describe, it, expect } from '@jest/globals';`,
    ``,
    `describe('UI States', () => {`,
  ];

  for (const screen of screens) {
    tests.push(`  describe('${screen}', () => {`);
    for (const state of ['loading', 'empty', 'error', 'normal']) {
      tests.push(`    it('renders ${state} state correctly', async () => {`);
      tests.push(`      // TODO: Mount component with ${state} props/state`);
      tests.push(`      // TODO: Verify expected elements are visible`);
      tests.push(`    });`);
      tests.push(``);
    }
    tests.push(`  });`);
    tests.push(``);
  }

  tests.push(`});`);
  return tests.join('\n');
}

// Main
function main() {
  const disciplineContent = readIfExists(path.join(projectRoot, 'discipline.md'));
  if (!disciplineContent) {
    disciplineError('discipline.md not found. Run discipline:hydrate first.');
    process.exit(1);
  }

  let config;
  try { config = readDisciplineConfig(projectRoot); } catch {
    disciplineError('Could not read discipline.md config.');
    process.exit(1);
  }

  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  const entities = extractEntities(disciplineContent);
  const endpoints = extractApiEndpoints(disciplineContent);
  const screens = extractScreens(path.join(projectRoot, '.discipline', 'packets'));

  let filesCreated = 0;

  // Backend adapter tests (always)
  const backendTests = generateBackendTests(entities, config);
  fs.writeFileSync(path.join(outputDir, 'backend-contracts.test.ts'), backendTests);
  filesCreated++;
  disciplineInfo(`Created: tests/generated/backend-contracts.test.ts (${entities.length} entities)`);

  // RLS tests (if Supabase)
  if (config.backendProvider === 'SUPABASE') {
    const rlsTests = generateRlsTests(entities, config);
    fs.writeFileSync(path.join(outputDir, 'rls-policies.test.ts'), rlsTests);
    filesCreated++;
    disciplineInfo(`Created: tests/generated/rls-policies.test.ts (${entities.length + 3} tables)`);
  }

  // API tests (if API lane or endpoints exist)
  if (endpoints.length > 0) {
    const apiTests = generateApiTests(endpoints);
    fs.writeFileSync(path.join(outputDir, 'api-endpoints.test.ts'), apiTests);
    filesCreated++;
    disciplineInfo(`Created: tests/generated/api-endpoints.test.ts (${endpoints.length} endpoints)`);
  }

  // UI state tests (if screens exist)
  if (screens.length > 0) {
    const uiTests = generateUiStateTests(screens);
    fs.writeFileSync(path.join(outputDir, 'ui-states.test.ts'), uiTests);
    filesCreated++;
    disciplineInfo(`Created: tests/generated/ui-states.test.ts (${screens.length} screens x 4 states)`);
  }

  console.log(`\n${filesCreated} test file(s) scaffolded in ${path.relative(projectRoot, outputDir)}/`);
  console.log('Each test has TODO markers. Fill in the implementation details.');
}

main();
